apiVersion: v1
kind: Config
current-context: terraform
clusters:
- name: ${name}
  cluster:
    certificate-authority-data: ${certificate_authority}
    server: ${endpoint}
contexts:
- name: terraform
  context:
    cluster: ${name}
    user: terraform
users:
- name: terraform
  user:
    token: ${token}
